Scala JMS HornetQ example
=========================

you need hornetq installed and running and the topic "/topic/exampleTopic" must
be already created.

to create it add the following::

     <queue name="ExpiryQueue">
        <entry name="/queue/ExpiryQueue"/>
     </queue>

to config/stand-alone/non-clustered/hornetq-jms.xml

then do::

        sbt console

and inside it::

        scala> (new org.marianoguerra.jms.TopicExample()).run()
        Sent message: This is a text message
        Consumer 1 Received message: This is a text message
        Consumer 2 Received message: This is a text message

packaging as one jar
--------------------

run the following command::

    sbt one-jar

and then::

    java -jar target/scala-2.9.2/scala-jms_2.9.2-0.1-one-jar.jar
